name: Deploy infra

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Specify the level folder to build (e.g., level1)"
        required: true

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Step 4: Initialize Terraform
      - name: Terraform Init
        working-directory: ${{ inputs.level }}
        run: |
          terraform init

      # Step 5: Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ inputs.level }}
        run: terraform apply -auto-approve

      # Step 6: Save Private Key to .pem File
      - name: Save Private Key
        working-directory: ${{ inputs.level }}
        run: |
          terraform output -raw private_key > my-key.pem
          chmod 400 my-key.pem

      # Step 7: Add Private Key to GitHub Secrets
      - name: Add Private Key to GitHub Secrets
        working-directory: ${{ inputs.level }}
        env:
          GITHUB_TOKEN: ${{ secrets.ADDSECRET }}
        run: |
          gh secret set MY_PRIVATE_KEY --body "$(cat my-key.pem)"